config_for: diagramupdate

# General
create_backup: True
create_output_file: True
log_changes: True

# Github config
parsefromgithub: True
commit_to_github: False
push_to_github: False
gitaccount: kthfspe
gitrepo: SA

# Outputs
logfilename: diagramupdate_log.yaml
outputsuffix: _output
backupsuffix: _backup
backup_directory: backups/
output_directory: outputs/

### Library update (work in progress) ###
# Inputs
# diagram_directory: Harness/
# diagram_filename: DeV17_harness.drawio
diagram_directory: LV_architecture/
diagram_filename: LV_physical_architecture.drawio
# diagram_directory: examples/LV_architecture/
# diagram_filename: LV_physical_architecture
# library_filename: Libraries/Harness.xml

# General changes
keep_properties: True
keep_attributes: False
keep_styles: True
keep_link: True
add_new_attributes: True
replace_attributes: True
replace_properties: True

# Specific changes
delete_attributes_for:
  PWR:
  - Unit
  - ValueMax
  - ValueMin

replace_property_value:
- OldValue:         # Add '-' for each new element
    SC_TSMS_precharge # Old value
  BlockTypes:       # Restrict to these specific blocktypes
    - LEMO
    - FCON
    - MCON
    - PWR
    - DIG
    - CAB
  NewValue:
    SC_TSMS_relays  # New value

replace_attribute_name:
- OldName:          # Add '-' for each new element
    NoOfPins        # Old value
  BlockTypes:       # Restrict to these specific blocktypes
    - ALL           # Do this for all blocktypes
  NewName:
    Pins            # New value
add_attributes_for:
  CAB:
    Weight:  '[kg]'
    Length:  '[mm]'
    ShieldingPoint:  '<name of the shielding net (leave epmty if not applicable)>'
  MCON:
    HVPins:  ''
  FCON:
    HVPins:  ''
