appdata:
- appbutton: Go
  appdisplayname: Search By Name
  appdisplaysubtext: Search any block or signal by name
  appfunctionname: searchnameapp
  apphelptext: Only the exact string match will be searched for. Not case sensitive
  apppackagename: searchname
  apppage: /searchbyname
  apptitle: searchbyname
- appbutton: Go
  appdisplayname: Find
  appdisplaysubtext: Find a string in any field in the DB
  appfunctionname: findfieldapp
  apphelptext: Checks for all fields
  apppackagename: findfield
  apppage: /findfield
  apptitle: findfield
- appbutton: Generate
  appdisplayname: Product Tree
  appdisplaysubtext: Generate a product tree based on the system architecture
  appfunctionname: producttreeapp
  apphelptext: Checks for all fields
  apppackagename: producttree
  apppage: /producttree
  apptitle: producttree
appdebug: true
connectorlistfilename: db/connectortypes.yaml
connectorlookuptablefilename: db/connector_lookup_table.yaml
BoardConnectors_matchfields:
- Family
- Gender
- Rows
LEMOConnectors_matchfields:
- Model
- AlignmentKey
- Series
- Gender
Connectors_checkfields:
- Pins
connector_maxpincount: 50
configyamlfilename: config.yaml
dbyamlfilename: db/db.yaml
debug: false
defaultDVfun: DV_architecture/DV_functional_architecture.drawio
defaultDVphy: DV_architecture/DV_physical_architecture.drawio
defaultHVfun: HV_architecture/HV_functional_architecture.drawio
defaultHVphy: HV_architecture/HV_physical_architecture.drawio
defaultLVfun: LV_architecture/LV_functional_architecture.drawio
defaultLVphy: LV_architecture/LV_physical_architecture.drawio
defaultpowerlist:
- +24V
- +5V
exampleDVfun: examples/DV_architecture/DV_functional_architecture
exampleDVphy: examples/DV_architecture/DV_physical_architecture
exampleHVfun: examples/HV_architecture/HV_functional_architecture
exampleHVphy: examples/HV_architecture/HV_physical_architecture
exampleLVfun: examples/LV_architecture/LV_functional_architecture
exampleLVphy: examples/LV_architecture/LV_physical_architecture
functional_blocks:
- ENVIN
- ENVOUT
- FE
functional_signals:
- FS
gitaccount: kthfspe
gitrepo: SA
ignore_blocktype:
- FRAME
- IGNORE
mergefields_concat:
- id
- Function
- target
- TargetName
- SourceName
mergefields_ignore_functional:
- Filename
- PageName
- PageId
- MetaParent
- x
- y
- label
- placeholders
- edge
- MetaParent
- width
- relative
- as
- source_x
- source_y
- target_x
- target_y
mergefields_ignore_physical:
- Assembling
- Filename
- PageName
- PageId
- MetaParent
- x
- y
- label
- placeholders
- edge
- width
- relative
- as
- source_x
- source_y
- target_x
- target_y
physical_blocks:
- SENS
- OTSC
- ECU
- NCU
- BAT
- FCON
- MCON
- LEMO
- ACT
- HMI
- PCU
- ENC
physical_signals:
- DIG
- ANA
- CAN
settingspagefields:
- debug
- defaultLVphy
- defaultLVfun
- defaultHVphy
- defaultHVfun
- defaultDVfun
- defaultDVphy
- exampleLVphy
- exampleLVfun
- exampleHVphy
- exampleHVfun
- exampleDVfun
- exampleDVphy
- dbyamlfilename
settingspagelistfields:
- ignore_blocktype
- physical_signals
- physical_blocks
- functional_signals
- functional_blocks
- defaultpowerlist
- mergefields_ignore_physical
- mergefields_ignore_functional
- mergefields_concat
